// AUTO-GENERATED by scripts/generate-pages.mjs
const CACHE = 'gap-0.9.16';
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil((async () => { for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k); await self.clients.claim(); })()));
self.addEventListener('fetch', (e) => { const req = e.request; if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return; e.respondWith((async () => { const cache = await caches.open(CACHE); const cached = await cache.match(req); const network = fetch(req).then((res) => { if (res && res.ok) cache.put(req, res.clone()); return res; }).catch(() => cached); return cached || network; })()); });
